force-app/main/default/objects/Sentinel_User_Info__c/Sentinel_User_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Sentinel User Info</label>
</CustomObject>

force-app/main/default/objects/Sentinel_User_Info__c/fields/DML_Url__c.field-meta.xml
<CustomField>
    <fullName>DML_Url__c</fullName>
    <label>DML Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Order_Sync__c.field-meta.xml
<CustomField>
    <fullName>Order_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Org_URL__c.field-meta.xml
<CustomField>
    <fullName>Org_URL__c</fullName>
    <label>Authentication URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/ProdDML_Url__c.field-meta.xml
<CustomField>
    <fullName>ProdDML_Url__c</fullName>
    <label>ProdDML Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/ProdOrg_URL__c.field-meta.xml
<CustomField>
    <fullName>ProdOrg_URL__c</fullName>
    <label>ProdOrg URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/ProdPassword__c.field-meta.xml
<CustomField>
    <fullName>ProdPassword__c</fullName>
    <label>ProdPassword</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/ProdUsername__c.field-meta.xml
<CustomField>
    <fullName>ProdUsername__c</fullName>
    <label>ProdUsername</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Quote_Sync__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Entitlement will be created in Sentinel when Quote will be selected from Sentinel Connect Settings page</description>
    <inlineHelpText>Entitlement will be created in Sentinel when Quote will be selected from Sentinel Connect Settings page</inlineHelpText>
    <label>Quote Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Request_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Request_Timeout__c</fullName>
    <label>Request Timeout</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Selected_Org__c.field-meta.xml
<CustomField>
    <fullName>Selected_Org__c</fullName>
    <label>Selected Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/StageDML_Url__c.field-meta.xml
<CustomField>
    <fullName>StageDML_Url__c</fullName>
    <label>StageDML Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/StageOrg_URL__c.field-meta.xml
<CustomField>
    <fullName>StageOrg_URL__c</fullName>
    <label>StageOrg URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/StagePassword__c.field-meta.xml
<CustomField>
    <fullName>StagePassword__c</fullName>
    <label>StagePassword</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/StageUsername__c.field-meta.xml
<CustomField>
    <fullName>StageUsername__c</fullName>
    <label>StageUsername</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Subscription_Sync__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Entitlement will be created in Sentinel when Subscription will be selected from Sentinel Connect Settings page</description>
    <inlineHelpText>Entitlement will be created in Sentinel when Subscription will be selected from Sentinel Connect Settings page</inlineHelpText>
    <label>Subscription Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoginSettingsController.cls
/*----------------------------------------------------
* @name           LoginSettingsController 
* @date           10 May 2020
* @description    This is a controller class for the setting page. 
* ------------------------------------------------------*/
public with sharing class LoginSettingsController {

    public Boolean                                        init                 = FALSE;
    @Testvisible private final Sentinel_User_Info__c      Settings;
    public string                                         option               {get;set;}

    public LoginSettingsController () {
        List<Sentinel_User_Info__c> rd = [SELECT Request_Timeout__c,
                                            Username__c, 
                                            Password__c, 
                                            Org_URL__c, 
                                            DML_Url__c,
                                            Order_Sync__c,
                                            ProdDML_Url__c,
                                            ProdOrg_URL__c,
                                            ProdUsername__c,
                                            ProdPassword__c,
                                            StageOrg_URL__c,
                                            StageDML_Url__c,
                                            StageUsername__c,
                                            StagePassword__c,
                                            Selected_Org__c,
                                            Quote_Sync__c,
                                            Subscription_Sync__c
                                        FROM Sentinel_User_Info__c WHERE Name='Primary User'];    
        system.debug('rd=' + rd );
        if (rd.size() == 1) {
            Settings = rd[0];
        } else {
            Settings = new Sentinel_User_Info__c(Name='Primary User' , Selected_Org__c = 'dev');
        }
    }
    
    public Sentinel_User_Info__c getSettings() {
        return Settings;
    }

    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('dev','Developer')); 
        options.add(new SelectOption('stage','Stage')); 
        options.add(new SelectOption('prod','Production')); 
        return options; 
    }

    public PageReference rdSave() {
        try {
            upsert Settings;
        } catch (Exception e) {
            system.debug('Error:' + e.getMessage());
        }
        PageReference pgRef = new PageReference('/apex/LoginSettings?mode=view');
        pgRef.setRedirect(true);
        return pgRef;
    } 
    
    public PageReference editRedirect() {
        PageReference pgRef = new PageReference('/apex/LoginSettings?mode=edit');
        pgRef.setRedirect(true);
        return pgRef;
    }

    public PageReference cancelRedirect() {
        PageReference pgRef = new PageReference('/apex/LoginSettings?mode=view');
        pgRef.setRedirect(true);
        return pgRef;
    }
}