force-app/main/default/objects/Order_JSON__c/Order_JSON__c.object-meta.xml
<CustomObject>
    <label>Order JSON</label>
    <nameField>
        <displayFormat>JSON-{00000}</displayFormat>
        <label>Order JSON Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order JSONs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_JSON__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order JSONs</relationshipLabel>
    <relationshipName>Order_JSONs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Thales__c.field-meta.xml
<CustomField>
    <fullName>Thales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Thales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentinel_Order_Field_Mapping__c/Sentinel_Order_Field_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Sentinel Order Field Mapping</label>
</CustomObject>

force-app/main/default/objects/Sentinel_Order_Field_Mapping__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_Order_Field_Mapping__c/fields/Field_Description__c.field-meta.xml
<CustomField>
    <fullName>Field_Description__c</fullName>
    <label>Field Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_Order_Field_Mapping__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_Order_Field_Mapping__c/fields/SF_Api_Field__c.field-meta.xml
<CustomField>
    <fullName>SF_Api_Field__c</fullName>
    <label>SF Api Field</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_Order_Field_Mapping__c/fields/sObjectName__c.field-meta.xml
<CustomField>
    <fullName>sObjectName__c</fullName>
    <label>sObjectName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/Sentinel_User_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Sentinel User Info</label>
</CustomObject>

force-app/main/default/objects/Sentinel_User_Info__c/fields/DML_Url__c.field-meta.xml
<CustomField>
    <fullName>DML_Url__c</fullName>
    <label>DML Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Order_Sync__c.field-meta.xml
<CustomField>
    <fullName>Order_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Org_URL__c.field-meta.xml
<CustomField>
    <fullName>Org_URL__c</fullName>
    <label>Authentication URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/ProdDML_Url__c.field-meta.xml
<CustomField>
    <fullName>ProdDML_Url__c</fullName>
    <label>ProdDML Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/ProdOrg_URL__c.field-meta.xml
<CustomField>
    <fullName>ProdOrg_URL__c</fullName>
    <label>ProdOrg URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/ProdPassword__c.field-meta.xml
<CustomField>
    <fullName>ProdPassword__c</fullName>
    <label>ProdPassword</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/ProdUsername__c.field-meta.xml
<CustomField>
    <fullName>ProdUsername__c</fullName>
    <label>ProdUsername</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Quote_Sync__c.field-meta.xml
<CustomField>
    <fullName>Quote_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Entitlement will be created in Sentinel when Quote will be selected from Sentinel Connect Settings page</description>
    <inlineHelpText>Entitlement will be created in Sentinel when Quote will be selected from Sentinel Connect Settings page</inlineHelpText>
    <label>Quote Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Selected_Org__c.field-meta.xml
<CustomField>
    <fullName>Selected_Org__c</fullName>
    <label>Selected Org</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/StageDML_Url__c.field-meta.xml
<CustomField>
    <fullName>StageDML_Url__c</fullName>
    <label>StageDML Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/StageOrg_URL__c.field-meta.xml
<CustomField>
    <fullName>StageOrg_URL__c</fullName>
    <label>StageOrg URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/StagePassword__c.field-meta.xml
<CustomField>
    <fullName>StagePassword__c</fullName>
    <label>StagePassword</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/StageUsername__c.field-meta.xml
<CustomField>
    <fullName>StageUsername__c</fullName>
    <label>StageUsername</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Subscription_Sync__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Entitlement will be created in Sentinel when Subscription will be selected from Sentinel Connect Settings page</description>
    <inlineHelpText>Entitlement will be created in Sentinel when Subscription will be selected from Sentinel Connect Settings page</inlineHelpText>
    <label>Subscription Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sentinel_User_Info__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPQTestDataFactory.cls
@isTest
public class CPQTestDataFactory{
    public static Account createAccount(String name, Id parentId){
        Account acc = new Account(Name = name, BillingCountry = 'USA');
        if (parentId != null){
            acc.ParentId = parentId;
        }
        insert acc;
        return acc;
    }

    public static Contact createContact(Id accountId){

        Contact con = new Contact();
        con.AccountId = accountId;
        con.FirstName = 'Test';
        con.LastName = 'Test LastName';
        con.Email = 'test@test.com';
        con.MailingCity = 'City';
        insert con;
        return con;
    }

    public static Contract createContract(Id accountId){
        Contract contract = new Contract(AccountId = accountId, ContractTerm = 12, StartDate = Date.today());
        insert contract;
        return contract;
    }

    /*
     * Code commeneted due to Subscription is not implemented properly
    public static SBQQ__Subscription__c createSubscription(Id accountId, Id contractId, Id productId, Decimal quantity, Decimal netPrice){
        return createSubscription(accountId, contractId, productId, quantity, netPrice, TRUE);
    }

    public static SBQQ__Subscription__c createSubscription(Id accountId, Id contractId, Id productId, Decimal quantity, Decimal netPrice, Boolean isInsert){

        Date endDate = Date.today().addYears(1);
        SBQQ__Subscription__c subs = new SBQQ__Subscription__c(SBQQ__Contract__c = contractId, Product2Id = productId, Quantity = quantity, AccountId = accountId, SBQQ__NetPrice__c = netPrice * quantity, SBQQ__SubscriptionEndDate__c = endDate);
        if (isInsert){

            insert subs;
        }
        return subs;
    }
    */

    public static SObject createQuote(Id accountId, Id opportunityId){
        return createQuote(accountId, opportunityId, null);
    }

    public static SObject createQuote(Id accountId, Id opportunityId, Id contactId){
        Schema.SObjectType quoteobj = Schema.getGlobalDescribe().get('Quote');
            sObject quote = quoteobj.newSObject();
    		quote.put('OpportunityId' , opportunityId); 
        	quote.put('Name' , 'Quote2');
        	quote.put('Status' , 'Presented');
	        quote.put(ContactId , contactId);
        insert quote;
        return quote;
    }

    public static SObject createQuoteLine(Id quoteId, Id productId, PricebookEntry priceEntry){
        Schema.SObjectType quotelineobj = Schema.getGlobalDescribe().get('QuoteLineItem');
            sObject line = quotelineobj.newSObject();
        	line.put('Product2Id' , productId); 
            line.put('QuoteId' , quoteId); 
            line.put('PricebookEntryId', priceEntry.Id); 
            line.put('Quantity' , 1); 
            line.put('UnitPrice' , 15);
       

        insert line;
        return line;
    }

    public static Opportunity createOpportunity(Id accountId, String type, String stage){
        Opportunity opportunity = new Opportunity(AccountId = accountId, Name = type, CloseDate = System.today().addMonths(12), StageName = stage, Pricebook2Id = Test.getStandardPricebookId());
        insert opportunity;
        return opportunity;
    }

    public static PricebookEntry createPricebookEntry(Id productId, Decimal amount){
        PricebookEntry pbEntry = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), Product2Id = productId, UnitPrice = amount, IsActive = true);
        insert pbEntry;
        return pbEntry;
    }

    public static OpportunityLineItem createOpportunityLine(Id opportunityId, Id productId, PricebookEntry priceEntry, Id lineItemId){
        OpportunityLineItem line = new OpportunityLineItem(Product2Id = productId, OpportunityId = opportunityId, PricebookEntryId = priceEntry.Id, TotalPrice = priceEntry.UnitPrice, Quantity = 1);

        insert line;
        return line;
    }

    public static Product2 createProduct(String name, Decimal amount){
        Product2 product = new Product2(Name = name, IsActive = true, Thales__c = true);

        insert product;
        return product;
    }

    public static Order_JSON__c createOrderJson(Id orderId){

        Order_JSON__c orderJson = new Order_JSON__c();
        orderJson.Order__c = orderId;
        insert orderJson;
        return orderJson;
    }

    public static Sentinel_User_Info__c createUserInfo(){
        //   SELECT Order_Sync__c,Quote_Sync__c, Subscription_Sync__c FROM Sentinel_User_Info__c
        Sentinel_User_Info__c userInfo = new Sentinel_User_Info__c();
        userInfo.Order_Sync__c = TRUE;
        userInfo.Quote_Sync__c = TRUE;
        userInfo.Subscription_Sync__c = TRUE;
        userInfo.Username__c = 'testuser';
        userInfo.PAssword__c = 'asdf';
        userInfo.StageUsername__c = 'testuser';
        userInfo.StagePassword__c = 'asdf';
        userInfo.ProdUsername__c = 'testuser';
        userInfo.ProdPassword__c = 'asdf';
        userInfo.Org_URL__c = 'https://test.salesforce.com/abc';
        userInfo.DML_Url__c = 'https://test.dmllesforce.com/xyz';
        userInfo.StageOrg_URL__c = 'https://test.salesforce.com/abc';
        userInfo.StageDML_Url__c = 'https://test.dmllesforce.com/xyz';
        userInfo.ProdOrg_URL__c = 'https://test.salesforce.com/abc';
        userInfo.ProdDML_Url__c = 'https://test.dmllesforce.com/xyz';

        userInfo.Name = 'Primary User';
        userInfo.Selected_Org__c = 'stage';
        insert userInfo;
        return userInfo;
    }

    public static Order createOrder(Account acc, Id pricebookId){
        return createOrder(acc, pricebookId, null);
    }

    public static Order createOrder(Account acc, Id pricebookId, Id contactId){

        Order o = new Order();
        o.Name = 'Test Order ';
        o.Status = 'Draft';
        o.EffectiveDate = system.today();
        o.EndDate = system.today() + 4;
        o.AccountId = acc.id;
        o.Pricebook2Id = Test.getStandardPricebookId();
        o.BillToContactId = contactId;
        o.ShipToContactId = contactId;
        insert o;
        return o;
    }

    public static OrderItem createOrderItem(Order ord, Product2 p, Id pricebookId){
        // Insert Order Item

        OrderItem i = new OrderItem();
        i.OrderId = ord.id;
        i.Quantity = 24;
        i.UnitPrice = 240;
        i.Product2id = p.id;
        i.PricebookEntryId = pricebookId;
        insert i;

        return i;
    }

    public static Sentinel_Order_Field_Mapping__c populateOrdFldMapng(String category, String objName, String fldApiName){

        Sentinel_Order_Field_Mapping__c ordFldMaping = new Sentinel_Order_Field_Mapping__c();
        ordFldMaping.Category__c = category;
        ordFldMaping.Field_Description__c = 'Test';
        ordFldMaping.Field_Type__c = 'Text';
        ordFldMaping.SF_Api_Field__c = fldApiName;
        ordFldMaping.sObjectName__c = objName;
        ordFldMaping.Name = objName + fldApiName;
        return ordFldMaping;
    }
}